#!/bin/bash
cd ${0%/*} || exit 1    # run from this directory

set -e # Any subsequent(*) commands which fail will cause the shell script to exit immediately

# The supported OpenFOAM version
OF_VER=8

check_openfoam()
{
    if [ -z ${WM_PROJECT} ]; then 
        echo "OpenFOAM environment not set."
        exit 1
    fi

    if [[ ! "$WM_PROJECT_VERSION" == "$OF_VER" ]]; then
        echo "Error: OpenFOAM-$WM_PROJECT_VERSION not supported."
        echo "       See other git branches for potential support."
        exit 1
    fi
}

how_to()
{
    echo "Error: Correct platform syntax ./Allwmake --platform MKL/OPENBLAS/STANDALONE" 
}


check_openfoam


if [ $CLEAN_ALL == true ]; then
    ./Allwclean
fi


wmake libso src/thermophysicalModels/chemistryModel
wmake tests/unittests


